### ISSUE TITLE
Get_cube exclude Rows with same attributes

### ISSUE THREAD

**Issue by YuryBolkonsky** [MicroStrategy/mstrio-py#1]
MSTR 10.11

I checked df = conn.get_cube(cube_id='F7B2DAC411E86F2AD1640080EFD5E4BB',limit=-1) and got 1083 rows instead of 1847.

I found issue. Even in response json we get only first row for rows with same attributes.

For example.
Country  Type date  Target
US B2B 2018-01-01 121
US B2B 2018-01-01 281 

In json response we will have only US B2B 2018-01-01 121.

I tried different ways but now there is only one slow solution with limit=1.

df = conn.get_cube(cube_id='F7B2DAC411E86F2AD1640080EFD5E4BB',limit=1)

But it takes more than 10 minutes for almost 2k rows.

**Comment by ssainz** [comment]
@YuryBolkonsky - Thanks for reporting this issue! I can reproduce it. As you confirm is within the library server. Therefore, could not fix it in mstrio, but we are working on a fix for next release.

**Comment by scottrigney** [comment]
@YuryBolkonsky this issue is now fixed in MicroStrategy 2019 Update 1. As @ssainz mentioned, the fix required a change on the Intelligence Server, not the mstrio-py or mstrio (for R) packages. Update 1 is available on the [MicroStrategy downloads](https://community.microstrategy.com/s/products) page.
