### ISSUE TITLE
Mstrio-py Migration - Migration Fail due to Timeout

### ISSUE THREAD

**Issue by DStavilaNI** [MicroStrategy/mstrio-py#174]
Dear Dev Team,

When performing project migrations, with a large number of objects, against an empty (new) project, the operation fails due to timeout errors. Typically, due to the failure, objects are only partially migrated and to overcome this, the migration has to done multiple times in order to complete it.

![image](https://github.com/MicroStrategy/mstrio-py/assets/35329597/0ba2eaf6-ff1d-4815-ae55-8c0ecbce7572)

The problem comes from the TIMEOUT set, as a constant, within the `package.py` module:
![image](https://github.com/MicroStrategy/mstrio-py/assets/35329597/d08d734a-6b81-4023-9cb5-3106de39361e)

and 

![image](https://github.com/MicroStrategy/mstrio-py/assets/35329597/1fdaeeab-e148-485a-8bcc-6bcfb09d4e6f)

If the TIMEOUT is increased to a larger value, the migrations can be completed successfully. 
My question would be if the TIMEOUT can be parametrized (for instance, as a parameter to the `migrate_package` method) or otherwise set dynamically depending on the size migration ?

Thank you,
Denis

**Comment by mgorskiMicroStrategy** [comment]
@DStavilaNI Hi, thanks for valuable feedback.
The migration package is going to be updated with 24.09 release. I will include this issue to be resolved in this update.
If you didn't log this issue to support please do so and share CS number here. It will help us make sure that issue is resolved and you will be informed by Support when it will be ready.

**Comment by apiotrowskiMicroStrategy** [comment]
Issue resolved with module official release. Closing
