### ISSUE TITLE
deprecated is_dossier use in mstrio-py/mstrio/project_objects /dossier.py list_dossiers

### ISSUE THREAD

**Issue by hustontrevor** [MicroStrategy/mstrio-py#180]
This internal code calling list_dossier blows up the terminal with:
 DeprecationWarning: function `is_dossier` is deprecated and will not be supported starting from mstrio-py 11.5.03. Please use function `is_dashboard` instead.

**Comment by mgorskiMicroStrategy** [comment]
@hustontrevor Due to rename of dossier to dashboard Dossier module, connected methods and functions were deprecated and will be removed with mstrio-py 11.5.03. To avoid printing this deprecation warning change your code to use only dashboard methods and functions. In this case it will be `list_dashboards`
