### ISSUE TITLE
Application code is fixed?

### ISSUE THREAD

**Issue by BramVe** [MicroStrategy/mstrio-py#32]
Currently the application code is fixed to 64 in the microstrategy.py file:
`application_code = 64`
This seems to be an identifier for Microstrategy that the origin is a Jupyter notebook.

This value is passed when logging in. This limits the API behaviour in some systems. Also, the package may be used outside Jupyter Notebook which may call for a different application code.

Is it strictly needed to add this application_code identifier? And if so, what would be appropriate application codes for different applications?

**Comment by p-kowal** [comment]
Hi BramVe!

Correct - this is a Jupyter Notebook application code. It shows the IServer which connector is trying to connect.
As per customer requests, we will be changing that with 11.2.3 release, so that the possibility for using only backend code (package used outside Jupyter Notebook in your sentence) will be more common.

For the details, please reach out to your MicroStrategy Tech Support Associate or Account Executive, so that we can be able to understand your situation even better and implement changes in the product, so that it is more useful and convenient for you.

Best regards,
Piotr Kowal
Data Science Principal Product Owner
